# ????? ?-MySQL ???
spring.datasource.url=jdbc:mysql://localhost:3306/football_league_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

# ?? ?????? ??????? ?? ?-MySQL ???
spring.datasource.username=root
spring.datasource.password=1234

# ????? ?-Dialect ???? MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ???? ???? ?????? ??????? ??????? ?????? ??? ????? ????
spring.jpa.hibernate.ddl-auto=create

# ???? ?????? ?-SQL ??????? (?????)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true